### ISSUE TITLE
Validar CNPJ retorna erro 404 no back-end

### ISSUE THREAD

**Issue by pedrro** [ThoughtWorksInc/registrolivre#100]
Ao validar um cnpj, está retornando um erro 404, que significa "não encontrado", até faz sentido, mas esse erro é usado quando algo dá errado.

Para corrigir isso o conselho é que caso o cnpj esteja válido deve retornar erro 200 "ok" e caso não for válido, deve ser 409 "conflito".

Também é necessário refatorar a diretiva de validar cnpj.

**Comment by dieselpardal** [comment]
Eu e Bruna pareamos a desenvolver os códigos.

**Comment by dieselpardal** [comment]
Verificação com sucesso.
