### ISSUE TITLE
É possível adicionar 2 sócios com cpf igual na mesma empresa

### ISSUE THREAD

**Issue by pedrro** [ThoughtWorksInc/registrolivre#104]
Ao criar/editar uma empresa é possivel adicionar mais de um sócio com o mesmo CPF.

Passos para reprodução:
1 - Adicionar campos para editar/criar uma empresa
2 - Adicionar um sócio
3 - Adicionar um segundo sócio com o mesmo cpf do primeiro
4 - clicar em salvar/contribuir

![Imgur](http://i.imgur.com/ncMSeVP.png)

**Comment by dieselpardal** [comment]
#dieselpardal e Bruna começamos desenvolver os códigos.

**Comment by inajaraleppa** [comment]
Não foi feito na tela de editar.

**Comment by dieselpardal** [comment]
Resolvi o item de Inajara.
