### ISSUE TITLE
Teste Exploratório - Campo número está como obrigatório.

### ISSUE THREAD

**Issue by inajaraleppa** [ThoughtWorksInc/registrolivre#106]
Ao cadastrar ou editar uma empresa o campo número não deve ser obrigatório, mas o botão salvar é desabilitado quando o valor do campo é apagado.

Como simular:
1. Entrar no Cadastrar ou Editar
2. Digitar um valor no campo Número e tirar o foco do campo
3. Apagar o valor do campo número e tirar o foco
4. O botão Salvar fica desabilitado mesmo o campo não sendo obrigatório.

**Comment by lipemorais** [comment]
Aguardando o fim do show case para commitar
