### ISSUE TITLE
Botão limpar não está limpando as mensagens de validação de CNPJ 

### ISSUE THREAD

**Issue by josigama** [ThoughtWorksInc/registrolivre#11]
No campo CNPJ ao apresentar as mensagens CNPJ já existente, Número incompleto e Número Inválido, ao clicar no botão Limpar as mensagens não estão sendo limpas. 
Passos para reproduzir: 
1) Acessar o sistema Registro livre
2) Preencher um número existente, incompleto ou inválido
3) Sistema exibe a mensagem
4) Clicar no botão limpar

**Comment by brunapereira** [comment]
Problema acontecendo novamente.
