### ISSUE TITLE
Teste Exploratório - Botão voltar deve ir para a listagem

### ISSUE THREAD

**Issue by inajaraleppa** [ThoughtWorksInc/registrolivre#110]
Ao clicar no botão voltar na visualização da emrpesa deve ir para a listagem de empresas, independente de qual a foi a última tela acessada.

**Comment by brunapereira** [comment]
Pode me dar o passo a passo de como reproduzir o erro?

**Comment by inajaraleppa** [comment]
Clicar em uma empresa na listagem > clicar em contribuir > clicar em cancelar > clicar em voltar : está voltando para o editar.
