### ISSUE TITLE
Teste Exploratório - Campos com validação incorreta.

### ISSUE THREAD

**Issue by inajaraleppa** [ThoughtWorksInc/registrolivre#111]
Campos CEP, Data de Abertura e Data de Emissão do documento estão com comportamentos incorretos na validação.

Passos para reproduzir:
1. Entrar na tela de Cadastro ou Editar
2. Digitar um valor incompleto sem todos os dígitos necessários na máscara no campo CEP (1234-1)ou Data de Emissão (12/12/1) ou Data de Abertura (05/02/199) e tira o foco do campo.

O comportamento errado é que o valor do campo está sendo apagado e a mensagem de Campo inválido exibida mesmo não sendo um campo obrigatório e o botão salvar fica desabilitado.

Comportamento esperado é:
1. Ao digitar um valor incompleto nos campos deve manter o valor e exibir a mensagem de campo inválido, mas não deve apagar o valor do campo.
2. Quando não houver valor nos campos que não são obrigatórios o botão de salvar deve estar habilitado.

**Comment by dieselpardal** [comment]
A maior parte da história está certa porém o campo de CEP não fica vermelho quando o valor está errado. Precisar corrigir só este ponto.

**Comment by dieselpardal** [comment]
Vamos passar a história como done e criar um nova história para criar a diretiva de validação para o cep
