### ISSUE TITLE
Mudar email do registro livre na tooltip de CNPJ

### ISSUE THREAD

**Issue by brunapereira** [ThoughtWorksInc/registrolivre#116]
*Contexto:*
A tooltip de CNPJ na página de editar mostra um email que não corresponde ao email do registro livre.

*Impacto no negócio:*
Os email serão enviados para outro endereço.

*Comportamento atual:*
Na tooltip de CNPJ na página de editar, o e-mail descrito é contato@registrolivre.com

*Comportamento esperado:*
O email correto a ser descrito na tooltip é contato@registrolivre.inf.br

**Comment by dieselpardal** [comment]
Verificação com sucesso!
