### ISSUE TITLE
Melhorar a barra de sucesso de upload

### ISSUE THREAD

**Issue by brunapereira** [ThoughtWorksInc/registrolivre#118]
Como um usuário do Registro Livre
Eu quero uma barra de carregamento mais expressiva
Para então eu entender se meu carregamento foi bem sucedido.

Contexto:
Ao validar com o cliente, ele pediu que a barra de carregamento dos arquivos fosse mais expressiva, pois a barra branca com os 100% não passa a mensagem numa primeira impressão.

1- Mudar barra de sucesso
Dado que eu sou um usuário do registro livre
Quando eu faço upload de um arquivo
Então eu quero ver uma barra de sucesso com as especificações a seguir.

#progressBar:
color: #fff 
text-align: center
font-weight: bold
border: 1px solid #3c763d
background-color: #67B168

2 - Alinhar botão de Verificar
Dado que eu sou um usuário do registro livre
Quando eu faço upload de um arquivo
Então o botão Verificar deve estar alinhado ao input de arquivo

<img width="116" alt="screen shot 2016-01-06 at 3 13 33 pm" src="https://cloud.githubusercontent.com/assets/4603866/12148929/38b83510-b488-11e5-8fcd-e0dea99d87e9.png">

**Comment by waldemarnt** [comment]
Por que ta blocked?

**Comment by waldemarnt** [comment]
Resolvi o item 2 e o alinhamento do texto também.

**Comment by josigama** [comment]
Foi checado e está de acordo com os requisitos.
