### ISSUE TITLE
Campos de CNPJ e CPF apagam quando são preenchidos incompletamente

### ISSUE THREAD

**Issue by brunapereira** [ThoughtWorksInc/registrolivre#119]
Comportamento atual:
Ao escrever um número de CNPJ ou CPF de sócio inválido e tirar o foco do campo, o número é apagado.

Impacto no negócio:
O não usuário pode mudar o foco para completar o campo posteriormente, ele deve preencher tudo. A experiência do usuário é impactada.

Comportamento esperado:
Ao incluir um CPF ou CNPJ faltando caracteres e tirar o foco do campo, deve ser mostrado um erro de CNPJ/CPF incompleto.

**Comment by dieselpardal** [comment]
Verificação com Sucesso.
