### ISSUE TITLE
Fazer o upload para S3 funcionar

### ISSUE THREAD

**Issue by lipemorais** [ThoughtWorksInc/registrolivre#125]
*Como* usuário do Registro Livre
*Quero* salvar um novo documento no cadastro de empresa 
*Então* jornalistas investigativos poderão ter acesso ao documento

**Critérios de aceitação**
*Dado* um usuário do Registro Livre
*Quando* salvar um documento
*Então* este deve ser salvo na S3

**Comment by lipemorais** [comment]
Inicialmente Maeda e Waldemar estão responsáveis por essa estória.

**Comment by maedabr** [comment]
Para possibilitar a configuração das chaves da amazon por ambiente, segue documentação do docker:

Substituição de variáveis do shell no docker-compose.yml:
https://docs.docker.com/compose/compose-file/#variable-substitution

Herança no docker-compose.yml:
https://docs.docker.com/compose/extends/

**Comment by waldemarnt** [comment]
Essa parte foi feita ja, dependemos agora das questões de segurança para finalizar essa estória.

**Comment by waldemarnt** [comment]
no momento essa história depende somente da #136
