### ISSUE TITLE
Deploy do RL para o ambiente de staging usando Docker

### ISSUE THREAD

**Issue by lipemorais** [ThoughtWorksInc/registrolivre#127]
O objetivo desta história é realizar o deploy do RL para o ambiente de staging através Go CD.

**É importante** verificar se os outros passos do pipeline não foram afetados.

**É importante** ter em mente que está história tem uma data limite para ser concluída do dia **26/01/2016** para que não atrase a entrega do MVP1

Está estória é a base para realizar o deploy para AWS EC2 por isso é a estória #128 depende desta.

**Comment by gpiress** [comment]
eu e @dieselpardal  fizemos. Precisamos trocar algumas permissões no servidor (acesso de escrita, leitura e execução pro usuário "registrolivre" nas pastas "build" e "build/libs" e no arquivo "build/libs/registrolivre.jar".

O nosso SCP enviava o jar para /home/registrolivre/app/registrolivre.jar. Porém, nossa imagem do Docker de Java procurava pelo JAR em "/home/registrolivre/build/libs/registrolivre.jar".

Essas foram as mudanças para a gente conseguir fazer o deploy pro servidor de staging automaticamente =).
