### ISSUE TITLE
Ferramenta de monitoramento para o RL

### ISSUE THREAD

**Issue by lipemorais** [ThoughtWorksInc/registrolivre#129]
O objetivo desta estória é encontrar uma ferramenta de monitoramento que possamos utilizar no Registro Livre. A sugestão inical é utilizar o New Relic. http://br.newrelic.com/

**Comment by lipemorais** [comment]
Este artigo fala de algumas ferramentas interessantes para monitoramento: http://www.sparringmind.com/best-web-analytics/

Este é uma ferramenta de monitoramento free: http://piwik.org/

**Comment by jonathanrz** [comment]
Vamos fechar essa história e criar uma nova pro New Relic da aplicação?
