### ISSUE TITLE
Iniciar a aplicação na hora que o servidor ligar

### ISSUE THREAD

**Issue by gpiress** [ThoughtWorksInc/registrolivre#131]
Como usuário do Registro Livre,
Gostaria que a aplicação iniciasse junto com o ligamento do servidor,
Para ter o menor downtime possível

Critérios de aceite:
- Servidor de staging sobe os containers do RL ao ligar
- Servidor da Amazon sobe os containers do RL ao ligar

**Comment by maedabr** [comment]
Corrigido.

Para testar:

- Reiniciar o servidor onde os containers do registro livre estão implantados e tentar acessar a aplicação. Deverá ser possível acessar o registro livre.

**Comment by waldemarnt** [comment]
:+1:
