### ISSUE TITLE
Adicionar variaveis de ambiente para as credenciais da AWS

### ISSUE THREAD

**Issue by waldemarnt** [ThoughtWorksInc/registrolivre#133]

**Comment by waldemarnt** [comment]
Foram adicionadas as seguintes variaveis de ambiente no docker compose
        - REGISTROLIVRE_AWS_ACCESS_KEY_ID=$REGISTROLIVRE_AWS_ACCESS_KEY_ID
        - REGISTROLIVRE_AWS_SECRET_ACCESS_KEY=$REGISTROLIVRE_AWS_SECRET_ACCESS_KEY
        - REGISTROLIVRE_AWS_BUCKET_NAME=$REGISTROLIVRE_AWS_BUCKET_NAME

Elas fazem referencia a uma variavel de ambiente do host.

**Comment by inajaraleppa** [comment]
Como testar se isso funciona? Para que essas variáveis serão utilizadas?

**Comment by waldemarnt** [comment]
Essas variaveis de ambiente servem para não expor as credenciais da amazon, e poder configurar dinamicamente por ambiente.

Para testar tem que adicionar essas variaveis de ambiente na maquina root e ver se a aplicação esta conseguindo ler elas.

**Comment by waldemarnt** [comment]
vamos esperar a #136 para poder testar no ambiente de produção onde são necessarias estas variaveis

**Comment by lipemorais** [comment]
Está estória poder ser validada entrando na máquina e verificando as variáveis de ambientes por lá.

**Comment by josigama** [comment]
Fizemos os testes e as variáveis só funcionam quando entramos na máquina da Amazon , exportamos as variáveis e rodamos o Registro Livre.                                                                                 A sugestão seria colocar as variáveis  na máquina do Agent e utilizar o script de deploy  para o S3.  ( Josi e Felipe - Pairing)

**Comment by maedabr** [comment]
Foi alterado o script "deployStaging.sh" para exportar as variáveis de ambiente p/ a máquina da amazon durante o deploy, dessa forma elas sempre são setadas no deploy.

**Comment by josigama** [comment]
Eu e Felipe realizamos a validação desta história testando as variáveis de ambiente na pipeline do GO.
