### ISSUE TITLE
Encontrar um serviço que simule o S3 para testes

### ISSUE THREAD

**Issue by maedabr** [ThoughtWorksInc/registrolivre#145]
Como o Registro Livre, quero que seja criado e/ou instalado um serviço que simule a API do S3 da Amazon, pois assim posso testar a integração de produção com a Amazon em desenvolvimento, testes e stage.

Para comprovar, verifique:
1) Deverá existir um serviço que simule algumas operações da Amazon, como PUT, POST, GET e informações no header dos requests
2) Esse serviço deverá manter um histórico de arquivos p/ que seja possível enviar e buscar
3) Deverá ser um serviço que rode num container Docker para facilitar na manutenção, execução e setup do ambiente para testes
4) O código do Registro Livre executado em produção deverá ser o mesmo nos testes internos com esse serviço fake
5) Esse serviço deverá ser capaz de lidar com a chave pública assinada que utilizamos para envio a Amazon (link: http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html)

**Comment by vtrbtf** [comment]
@maedabr Algumas ferramentas que eu achei bacana: 
- [S3Ninja](https://github.com/scireum/s3ninja)
- [s3-server](https://github.com/PredicSis/s3-server)

**Comment by waldemarnt** [comment]
@vtrbtf eu e o @maedabr estamos implementando o S3Ninja, esta funcionamento muito bem é bem interessante mesmo :)

**Comment by maedabr** [comment]
O @waldemarnt, @dieselpardal e eu colocamos o S3Ninja p/ simular a amazon nos ambientes locais e stage. Tivemos alguns problemas na execução dos testes funcionais, mas não conseguimos reproduzir hoje, ou seja, o pipeline está sendo executado com sucesso.

**Comment by josigama** [comment]
Eu e Felipe seguimos os passos descritos na história e validamos todo os passos com sucesso.
