### ISSUE TITLE
[Env:Dev] Porta local é 80 e não 8080

### ISSUE THREAD

**Issue by vtrbtf** [ThoughtWorksInc/registrolivre#146]
Segundo a documentação do projeto, o acesso a aplicação é pela porta 8080, porém depois de provisionar todo o ambiente local, percebi que o bind é somente com a porta 80. 

Então o acesso para mim esta sendo por: `http://192.168.99.100:80/#/`

**Comment by gpiress** [comment]
Tem razão! 

Vou alterar os docs, mas caso o erro aconteça novamente:
A porta em que a aplicação é servida pode ser checada em `docker-compose.yml`, na linha 5, no mapeamento de portas do container `reglivre`.

`80:8080`

O primeiro número é a porta que a aplicação será servida =)

**Comment by josigama** [comment]
Eu e Felipe checamos o código e testamos a URL da aplicação conforme descrito na história e está OK.
