### ISSUE TITLE
Status do sócio não é salvo como ativo

### ISSUE THREAD

**Issue by josigama** [ThoughtWorksInc/registrolivre#149]
O status "ativo" do sócio é ignorado tanto na criação quanto na edição de empresas.

Comportamento atual:
- Criar ou editar uma empresa, marcar o sócio como ativo, salvar e observar que o status é exibido como "Não ativo"

Comportamento desejado:
- Criar ou editar uma empresa, marcar o sócio como ativo, salvar e observar que o status dever ser exibido  como "Ativo".

**Comment by josigama** [comment]
![1](https://cloud.githubusercontent.com/assets/13666514/12959086/f51cd8ec-d01b-11e5-9ed4-28a79e617713.png)
![2](https://cloud.githubusercontent.com/assets/13666514/12959094/fc81d84e-d01b-11e5-9ad2-aa412fb6129d.png)
![screen shot 2016-02-10 at 5 29 32 pm](https://cloud.githubusercontent.com/assets/13666514/12959095/fc9fbbe8-d01b-11e5-8e50-f4055eb6dd9b.png)

**Comment by maedabr** [comment]
Corrigido e criado um testes funcional para cobrir esse caso.

**Comment by waldemarnt** [comment]
O comportamento de salvar como "Ativo" está funcionando, a na pagina de visualização está mostrando correto, como na foto abaixo:
<img width="251" alt="screen shot 2016-02-11 at 3 21 42 pm" src="https://cloud.githubusercontent.com/assets/5835706/12984288/2c45053e-d0d4-11e5-9f06-554da8f14fb4.png">

Mas se eu retornar a pagina de edição o checkbox estara desmarcado e caso eu submenta o formulário ele irá remover o status de "Ativo" do sócio.
<img width="238" alt="screen shot 2016-02-11 at 3 22 02 pm" src="https://cloud.githubusercontent.com/assets/5835706/12984342/676e328e-d0d4-11e5-87c7-084344376541.png">

**Comment by josigama** [comment]
Realizei o teste e apresentou o seguinte problema: 
Ao incluir quatro sócios ativos e apagar o terceiro o sistema remove o ultimo sócio cadastrado e o terceiro permanece. 

Segue imagem abaixo:
