### ISSUE TITLE
Minificação dos arquivos do Registro Livre

### ISSUE THREAD

**Issue by adrianelemos** [ThoughtWorksInc/registrolivre#154]
É importante juntar os arquivos JS e CSS para usar menos recursos do Route 53, evitando gastos desnecessários para o cliente e melhorando a performance. Essa US deve ser feita antes do deploy na pipeline.

**Comment by otaviocarvalho** [comment]
Também é possível (no futuro) comprimir os arquivos minificados com gzip, mas é necessário habilitar o suporte no servidor web Apache/Nginx. 

Exemplo: https://varvy.com/pagespeed/enable-compression.html
