### ISSUE TITLE
Link do Twitter está com uma URL estranha

### ISSUE THREAD

**Issue by lqust** [ThoughtWorksInc/registrolivre#156]
O link está como https://twitter.com/home?status=http:http://ec2-54-232-246-149.sa-east-1.compute.amazonaws.com:5000/

Isso me oferece crar um tweet com o conteúdo: "http:http://ec2-54-232-246-149.sa-east-1.compute.amazonaws.com:5000/"

**Comment by dieselpardal** [comment]
Resolvido.
