### ISSUE TITLE
Sistema não deleta o sócio correto

### ISSUE THREAD

**Issue by josigama** [ThoughtWorksInc/registrolivre#161]
Realizei alguns testes e apresentou o seguinte problema: 
Ao incluir quatro sócios ativos e apagar o terceiro o sistema remove o ultimo sócio cadastrado e o terceiro permanece. 
Segue imagem do problema: 
![screen shot 2016-02-15 at 7 23 34 pm](https://cloud.githubusercontent.com/assets/13666514/13060686/596332d6-d41a-11e5-9426-297974259d22.png)
Apagar o terceiro sócio e salvar: 
![screen shot 2016-02-15 at 7 29 29 pm](https://cloud.githubusercontent.com/assets/13666514/13060714/7ad5e490-d41a-11e5-8dca-e9971f0717f3.png)
Permanece o terceiro sócio e o quarto sócio é apagado. 

Necessário incluir nessa história testes.

**Comment by gpiress** [comment]
Preciso criar os testes do controller agora, mas a princípio tá ok. Amanhã eu crio os testes =)
