### ISSUE TITLE
Impedir alterar CNPJ no Editar Empresa

### ISSUE THREAD

**Issue by gpiress** [ThoughtWorksInc/registrolivre#163]
Não permitir que um usuário altere o CNPJ de uma empresa, mesmo que ele mude o objeto JavaScript de request pelo Console.

Para testar se é possível ainda alterar, faça o seguinte fluxo:

1. Cadastre uma empresa com CNPJ A
2. Abra a tela de Edição dessa empresa
3. Altere algum campo
4. Abra o Console (DevTools)
5. Encontre o objeto "company" no scope da página
6. Altere o CNPJ do scope para B
7. Clique em Enviar
8. Clique para visualizar a Empresa. 

- Se o erro continuar, estará com CNPJ B. 

- Se tiver sido corrigido, estará com CNPJ A.

Checar commit ae3b02193cf65e906d86e7af348af79853b1b2c9 (https://github.com/ThoughtWorksInc/registrolivre/commit/ae3b02193cf65e906d86e7af348af79853b1b2c9)

**Comment by dieselpardal** [comment]
Aprovado.
