### ISSUE TITLE
Enviar documento de uma empresa

### ISSUE THREAD

**Issue by OtavioRMachado** [ThoughtWorksInc/registrolivre#3]
Um(a) Colaborador(a)
Deseja compartilhar o documento de registro de uma empresa
Para que outros jornalistas tenham acesso ao documento.

Critérios de Aceitação:
* Aceitar somente PDF
* Aceitar arquivo até 5mb
* Salvar arquivo
* Informar:
  * Campo vazio;
  * Campo obrigatório;
  * Formato inválido;
  * Sucesso;
  * Tamanho superior ao aceitável

**Comment by josigama** [comment]
Story Card finalizada por Cláudio Bustamante.
