### ISSUE TITLE
Fix Application Server

### ISSUE THREAD

**Issue by lipemorais** [ThoughtWorksInc/registrolivre#34]
Investigate why application is not working in CI/Production.

**Comment by lipemorais** [comment]
We just redeployed in Go CD to make it work again. We still don't know why it wasn't working this morning.

**Comment by pedrro** [comment]
Application server is not creating new companies

**Comment by pedrro** [comment]
felipe and guilherme will fix it again

**Comment by lipemorais** [comment]
We fix it adding the Amazon key to .profile but the upload can't be completed because of Amazon credentials. One tip is that the server can't complete the communication with Amazon S3 Server. A good action is talk with TechOps guys to check it.
Any problem please, talk with @pedrro
