### ISSUE TITLE
Apply filter on JacocoReport

### ISSUE THREAD

**Issue by pedrro** [ThoughtWorksInc/registrolivre#42]
Should apply a filter on jacocoReport to exclude unnecessary classes.

**Comment by pedrro** [comment]
I applied a filter on jacoco that will exclude the packages utils and configurations, so, right now the report is more clean to visualize... An improvement for this task is find a way to exclude the class Application.java from report. A solution is create a package just to this class.

**Comment by deniscostadsc** [comment]
@pedrro 

Should we be able to see these reports at Go Server? I don't have a up and runnig VM, I tried to find it, but I couldn't.

**Comment by pedrro** [comment]
@deniscostadsc No, it's not available at GO server. :( But you can find the report in your local machine, we have a session on wiki to find the report.
