### ISSUE TITLE
Página de detalhes da empresa - pt.1

### ISSUE THREAD

**Issue by josigama** [ThoughtWorksInc/registrolivre#44]
Should just show the filled fields about company: 
- Fantasy name
- CNPJ
- Social Reason
- Address (Street, number, complement, city, estate, zip code)
- Opening date
- Emission date
- Partner (Name, CPF. status)
- Document(PDF) to download

**Comment by josigama** [comment]
Add dash as a placeholder for empty fields.

**Comment by pedrro** [comment]
Está faltando testes funcionais.

**Comment by pedrro** [comment]
Essa estória voltou porque não está aparecendo o parceiro da empresa.

**Comment by josigama** [comment]
Finalizado os testes funcionais dessa estória.
