### ISSUE TITLE
Create error page in the frontend

### ISSUE THREAD

**Issue by ebragaparah** [ThoughtWorksInc/registrolivre#48]
We need to create a 404 page for our project because we dont have it yet.

**Comment by pedrro** [comment]
Já está definida o layout dessa página de erro?

**Comment by lipemorais** [comment]
Não, seria bom ver com o XD isso.

**Comment by josigama** [comment]
Neste momento não estamos considerando melhorias no layout da página de erro, pois não é nossa prioridade para o MVP.
