### ISSUE TITLE
[Usability] Main Menu

### ISSUE THREAD

**Issue by luismizutani** [ThoughtWorksInc/registrolivre#52]
Change main menu to make it simpler and intuitive:

1. Eliminate the item "Busca" from the main menu bar. This is a not needed as it repeats the action of the logo, which is to take the user back to the homepage. (Check with users if the logo as a link for homepage is really intuitive. Some user groups do not find that intuitive, even if this seems to us so usual)

2. Change the item "Listar Empresas" to simply "Empresas"

3. Reorder main menu links to:
Home > Cadastrar Empresas > Empresas

**Comment by josigama** [comment]
Task checked and is OK
