### ISSUE TITLE
[Usabilidade] Formulário de sócio

### ISSUE THREAD

**Issue by luismizutani** [ThoughtWorksInc/registrolivre#53]
A few improvements here:
- [x] Focus of the partner form (editing mode):  When user click to "adicionar sócio", the screen does not move to show this part of the form in the main screen area. This can cause the user to get confuse, and to not know that the form is enabled. 
- [x] Active partner: Bring the check box of "sócio ativo" disabled as the default setting. This is a non-mandatory info.
- [x] Tooltip for Active partner:  we can include a tooltip explaining what is an "sócio ativo". (ex: a small icon of interrogation that brings a description when you mouse it over.

**Comment by brunapereira** [comment]
Alguém sabe qual é a descrição para o tooltip do campo sócio ativo?

**Comment by pedrro** [comment]
Então, não tem nenhuma descrição ainda, talvez seria legal perguntar para o @luismizutani

**Comment by luismizutani** [comment]
Talvez devêssemos ver a descrição com o próprio cliente, não?

**Comment by luismizutani** [comment]
Podemos ter algo inicialmente como marcação

**Comment by mauricioborges** [comment]
@brunapereira, fechamos a tarefa e abrimos outra para colocar o tooltip? ou voltamos para ser corrigido?

**Comment by mauricioborges** [comment]
criada tarefa #83 para melhorar a mensagem
