### ISSUE TITLE
Visualização da empresa - Página de detalhes - pt.2

### ISSUE THREAD

**Issue by ebragaparah** [ThoughtWorksInc/registrolivre#54]
**DESCRIÇÃO**
COMO... um contribuidor do Registro Livre
GOSTARIA... saber quais informações da empresas estão faltando em sua página de detalhes
ASSIM... posso direcionar melhor meus esforços de pesquisa e melhorar a qualidade do serviço prestado pelo site.

**CRITÉRIOS DE ACEITAÇÃO**

1.
DADO que selecionei visualizar os detalhes de uma empresa.
QUANDO os campos "Endereço","Estado" e "Cidade" estiverem vazios no momento da visualização da empresa.
ENTÃO os nomes destes campos deverão aparecer listados em um bloco de informações á parte na parte inferior da tela de detalhes da empresa.

2.
DADO que selecionei visualizar os detalhes de uma empresa
QUANDO os campos "CNPJ", "Razão Social"e "Nome Fantasia"estiverem preenchidos no momento da visualização.
ENTÃO estes campos devem aparecer no topo da página de visualização com seus respectivos valores.

3.
DADO que cliquei no botão CONTRIBUIR.
QUANDO os campos que estavam listado na página de visualização da empresa como não preenchidos forem exibidos.
ENTÃO estes campos devem estar highlighted na cor (#FFA500).

**OBSERVAÇÕES ADICIONAIS**
Acima do bloco de campos não preenchidos deverá ter uma frase alertando usuário para as informações incompletas. (Ver imagem exemplo). O botão "call to action" para complementar o cadastro daquela empresa será parte de outra estória.

**CONCEITO DE INTERFACE (clique na imagem para abrir no sentido correto)**
![registrolivre_detalhe_part2](https://cloud.githubusercontent.com/assets/3470102/11047719/1fc4c7e8-871b-11e5-8ae3-3ad404197c10.jpg)

**Comment by luismizutani** [comment]
I understood that the first part would bring content available (regardless if the field is mandatory or not).
Ans the second part would bring the content not available (not filled by user), so we can call people to action to compliment missing content.

**Comment by ebragaparah** [comment]
Ah, nice! Thats it! You're right, @luismizutani! Should I change it in the first comment or keep the history?

**Comment by luismizutani** [comment]
Perhaps we should make the design in a way that would encourage users to edit and compliment missing info.

**Comment by josigama** [comment]
Conforme alinhado com Marina, Bruna e Gabriel, estamos retornando essa  estória para que seja incluso melhorias: 

1. Os campos que aparecem no bloco de Dados não preenchidos não devem aparecer junto com os dados preenchidos da empresa.
Hoje está sendo exibido o campo com "-", mas o comportamento deveria ser aparecer apenas na parte de Dados não preenchidos.
2. A Estrutura Societária não deve aparecer caso não possua sócios cadastros, o comportamento correto é exibir nos dados não preenchidos uma label escrita "Sócios" caso não tenha sócios cadastrados.
3. Adicionar mensagem no lugar do texto "Dados não preenchidos".
Mensagem: "Dados da empresa ainda não cadastrados, nos ajude colaborando com essas informações" - Outras sugestões de frases são bem vindas. 
4. Quando o campo "Emissão de documentos" não estiver preenchido ele deverá ser listado nos dados não preenchidos. Hoje essa informação não está sendo exibida.
