### ISSUE TITLE
Validar prioridade estória (lista de resultados)

### ISSUE THREAD

**Issue by luismizutani** [ThoughtWorksInc/registrolivre#59]
Item para incluir na agenda da reunião com cliente

Validar com cliente qual importância para o o MVP das estórias:
1. Ter data do documento na lista
2. Habilidade de selecionar quantos resultados a lista exibirá
3. Download em lote (considerando que ainda temos poucos registros)
4. Reordenar lista (considerar cenários onde isto é necessário e quão frequente isto ocorre).

Acreditamos que alguns dos itens acima só serão importantes quando tivermos um bom volume de dados. Um exemplo disto é selecionado o numero de resultados exibidos na lista

**Comment by brunapereira** [comment]
1 - não rpecisa
2 - a paginação resolve. No resultado da busca, pensar em uma abordagem diferente.
3 - sim!
4 - já está ordenando por nome e estado.
