### ISSUE TITLE
Sugestão p/ storage! 

### ISSUE THREAD

**Issue by nofxx** [ThoughtWorksInc/registrolivre#6]
Bom dia conterrâneos, segue uma idéia para vocês:

CouchDB como storage, é perfeito p/ essa aplicação: 
- Pessoas poderiam clonar e sincronizar o banco para uso local, 
- Documentos seriam gravados com controle de revisão (tudo isso já eh padrão no couch)
- Não seria necessario esquema prévio de documentacao ou o q será relacionado à empresa.

Tudo bem que isso pode ser feito em SQL, mas demanda código e o ponto 1 por ex ñ iria ser diferente de um pgdump pgrestore =/

**Comment by annekellyc** [comment]
Olá @nofxx ,

A sua ideia é bem vinda para a nossa aplicação e faz sentido os pontos que você citou.
No início do projeto tivemos até o levantamento de usar um banco de dados NoSQL (mongoDB ou couchDB).
Temos uma provável issue a ser desenvolvida futuramente na aplicação que seria um dashboard onde o usuário teria a possibilidade de "linkar/relacionar" documentos agrupando os mesmos dentro de uma categoria ou tags, etc. Para o desenvolvimento desse dashboard pensamos que poderia ser interessante um banco de dados NoSQL. Para o que temos  até agora desenvolvido não vimos que ainda é crítico essa mudança para NoSQL. Mas futuramente quando tivermos melhor o que será exatamente este dashboard, pode ser que a migração para NoSQL seja interessante.

Por enquanto, a ideia é só armazenar os documentos em uma instância S3.

Obrigada!

=)
