### ISSUE TITLE
Adicionar máscara na visualização do CPF do sócio

### ISSUE THREAD

**Issue by josigama** [ThoughtWorksInc/registrolivre#62]
Conforme o padrão de visualização do CNPJ incluir também a máscara no CPF do Sócio.

**Comment by inajaraleppa** [comment]
Os CPFs cadastrados antes da correção não estão com a máscara, apenas os adicionados após a correção. Está ok este comportamento?

**Comment by pedrro** [comment]
Sim, porque no banco de dados eles estão sem a mascara. No caso, a mascara é aplicada quando o registro é salvo e não quando ele é mostrado
