### ISSUE TITLE
Adicionar testes para múltiplos sócios

### ISSUE THREAD

**Issue by josigama** [ThoughtWorksInc/registrolivre#63]
Foi adicionado teste para um único sócio é necessário testar o comportamento quando temos mais de um.

**Comment by brunapereira** [comment]
qual teste?

**Comment by brunapereira** [comment]
Não precisa adicionar teste para múltiplos sócios porque o código necessário para adicionar um sócio é o mesmo utilizado para adicionar mais de um sócio.
