### ISSUE TITLE
Revisar informações do README

### ISSUE THREAD

**Issue by mauricioborges** [ThoughtWorksInc/registrolivre#65]
Há referências a AWS que não são mais válidas. Verificar se a wiki tem alguma informação ultrapassada, especialmente as instruções de instalação e o FAQ

**Comment by pedrro** [comment]
Tem que ser feito depois da implementação do docker na infra.

**Comment by inajaraleppa** [comment]
Inserir o download do docker nos pré requisitos.
Retirar o vagrant dos pré requisitos.
Alterar o build do docker: colocar o comando ./gradlew deployDocker para rodar o docker e colocar o comando ./gradlew functionalTest para rodar os testes funcionais.
