### ISSUE TITLE
Foco na mensagem de sucesso do cadastro

### ISSUE THREAD

**Issue by luismizutani** [ThoughtWorksInc/registrolivre#69]
Quando a mensagem de sucesso no cadastro de uma empresa é exibida. A mensagem é exibida na primeira rolagem. Isto faz com que o usuário não veja a mensagem corretamente. A mensagem deve ser exibida na mesma rolagem na qual o usuário finalizou o cadastrop

**Comment by mauricioborges** [comment]
verificado por @dieselpardal e eu. ok!
