### ISSUE TITLE
Mensagem para nenhuma empresa cadastrada

### ISSUE THREAD

**Issue by inajaraleppa** [ThoughtWorksInc/registrolivre#70]
Na listagem de empresas quando não existe empresa cadastrada está sendo exibida uma mensagem como se fosse uma linha da tabela.
Alterar  para não aparecer a tabela quando não houver registros.
Alterar para aparecer apenas a mensagem centralizada e em negrito.

<img width="830" alt="screen shot 2015-11-23 at 6 21 52 pm" src="https://cloud.githubusercontent.com/assets/2325187/11348736/69b86450-920f-11e5-939f-2f241aa44def.png">

**Comment by dieselpardal** [comment]
A situação está ok!
