### ISSUE TITLE
Criar página "Sobre"

### ISSUE THREAD

**Issue by brunapereira** [ThoughtWorksInc/registrolivre#72]
Como um usuário 
Eu quero acessar uma página informativa 
Para que eu possa saber a proposta do projeto e saber como contribuir.

Obs.: O conteúdo está na página do RL da aceleradora.

1: Adicionar link para a página "Sobre" no footer.

2: Adicionar uma nova página estática que vai conter as informações

3: A página deve conter o título "Sobre"

**Comment by inajaraleppa** [comment]
Separadas as palavras "O" e o "Registro Livre" que estavam grudadas.
Corrigido o problema de hover nos links do rodapé.

**Comment by inajaraleppa** [comment]
Alterando icone do rodapé.
