### ISSUE TITLE
Mudar nome dos botões

### ISSUE THREAD

**Issue by brunapereira** [ThoughtWorksInc/registrolivre#73]
1: Mudar nome do botão "Download de PDF" na página da empresa para "Baixar documento"

2: Mudar nome do botão "Ver Registro" na lista de empresas para "Ver Documento"

**Comment by mauricioborges** [comment]
@dieselpardal e eu verificamos.

**Comment by josigama** [comment]
Estou reabrindo essa tarefa, pois está apresentando o seguinte comportamento: 
Comportamento atual: 
- Ao clicar no botão "Ver documento" na lista de empresas o sistema abre uma nova aba para visualização do documento e ao retornar para a lista de empresa eu visualizo o detalhamento da empresa ao qual eu cliquei para ver o documento. 

Comportamento esperado:  
Quando eu clicar no botão "Ver documento" e retornar para a listagem de empresa devo visualizar a listagem de empresas.
