### ISSUE TITLE
Substituir strings literals de rotas por constantes

### ISSUE THREAD

**Issue by brunapereira** [ThoughtWorksInc/registrolivre#80]
No factory companies, app.js, new company controller e search company controller usam rotas com strings. O ideal seria extrair essas strings para variáveis que possam ser reutilizadas.

**Comment by gpiress** [comment]
Esse blog post é legal para quem for fazer essa história: http://twofuckingdevelopers.com/2014/06/angularjs-best-practices-001-constants/
