### ISSUE TITLE
Mover validações que estão feitas no controller para outro lugar

### ISSUE THREAD

**Issue by brunapereira** [ThoughtWorksInc/registrolivre#81]
Várias validações estão sendo feitas no new company controller, que poderiam estar sendo feitas de outra forma no factories company.

**Comment by brunapereira** [comment]
alguém fez essa estória? se sim, quem?

**Comment by pedrro** [comment]
Você fez isso não? durante aquelas refatorações..

**Comment by brunapereira** [comment]
Sim heheheheh
