### ISSUE TITLE
Editar dados de uma empresa

### ISSUE THREAD

**Issue by pedrro** [ThoughtWorksInc/registrolivre#82]
Um colaborador
Deseja alterar ou incluir dados de uma empresa
Para corrigir ou completar os dados da empresa.

Critérios de Aceitação:
* Salvar - Nome Fantasia/ Razão Social/ Endereço/ Numero/ Complemento/ Estado/ Cidade/ CEP/ Data de Abertura
* Nome Fantasia - Campo Obrigatório
Cria botão "editar" na página da empresa.

**Comment by dieselpardal** [comment]
Ivan e Bruna ja implementamos nova pagina de editar.

**Comment by lipemorais** [comment]
Tem muito trabalho repetido no controller de edit que já está feito no new-company-controller.

**Comment by dieselpardal** [comment]
Irei a refactorar no controller de edit.

**Comment by josigama** [comment]
A estória foi retornada para "Ready", pois não está sendo exibido o  asterisco ( * ) de campos obrigatórios: 
-Arquivo
- CNPJ
- Nome Fantasia
