### ISSUE TITLE
Substituir dados fake do tooltip e termos de uso

### ISSUE THREAD

**Issue by mauricioborges** [ThoughtWorksInc/registrolivre#87]
Conforme discutido na issue #53 a mensagem vai ser melhorada posteriormente

**Comment by inajaraleppa** [comment]
Quando o cliente enviar o tooltip do sócio ativo e os termos de uso, substituir nas páginas.

**Comment by brunapereira** [comment]
Observando as páginas entendi o que Inajara falou.
Sim, teria que trocar o tamanho dos títulos nas páginas Sobre, Colabore e Termos de Uso.

O Google indexa as páginas através do título h1, por isso devemos ter somente uma tag h1 nas nossas páginas.  Além disso, por questões de design, o maior título da página deve ser o nome da empresa/negócio/produto. Por isso eu sugeri a mudança. 

Eu vou completar essa estória apenas mudando os textos e nós validamos a minha sugestão. :)

**Comment by inajaraleppa** [comment]
Adicionando texto novo do sócio na tela de edição.
