### ISSUE TITLE
Bug no highlight do formulário de cadastro de empresa

### ISSUE THREAD

**Issue by lipemorais** [ThoughtWorksInc/registrolivre#92]
Bug no highlight do formulário de cadastro de empresas.

Ao tentar adicionar sócios na empresa, caso um CPF  esteja errado o highlight aparece nos dois formulários mesmo  que o segundo CPF esteja correto.
![screen shot 2015-12-07 at 6 22 51 pm](https://cloud.githubusercontent.com/assets/5021565/11638721/92ce8a08-9d0f-11e5-80e5-282eed445e70.png)

**Comment by pedrro** [comment]
A estória voltou, por causa que a validação de cpf valido não está funcionando.
