### ISSUE TITLE
Mini busca não apaga os dados quando muda de página

### ISSUE THREAD

**Issue by josigama** [ThoughtWorksInc/registrolivre#93]
Ao clicar nas abas cadastrar empresa ou empresa e buscar alguma informação na mini busca. Ao mudar de página o sistema não apaga o último dado pesquisado. 

Estória associada: #68

Para reproduzir o comportamento:
Acessar http://10.27.1.58:5000/#/cadastro ou http://10.27.1.58:5000/#/empresas
Usar a mini busca para pesquisar alguma empresa
Acessar http://10.27.1.58:5000/#/cadastro ou http://10.27.1.58:5000/#/empresas
O texto pesquisado estará ali.

Comportamento esperado
Acessar http://10.27.1.58:5000/#/cadastro ou http://10.27.1.58:5000/#/empresas
Usar a mini busca para pesquisar alguma empresa
Acessar http://10.27.1.58:5000/#/cadastro ou http://10.27.1.58:5000/#/empresas
O campo de mini busca deverá estar vazio.

**Comment by inajaraleppa** [comment]
Não está cumprindo o comportamento esperado, pois deve limpar o campo apenas quando muda de página e não quando clica no enter ou no ícone de pesquisar.
