### ISSUE TITLE
Comportamento errado no botão cancelar na tela de edição

### ISSUE THREAD

**Issue by inajaraleppa** [ThoughtWorksInc/registrolivre#96]
Ao entrar na tela de edição e clicar no botão cancelar os campos estão sendo limpos.
O comportamento correto deve  ser voltar para a tela de visualização de empresa.

Critérios de aceitação
1. Ao clicar no botão cancelar deve voltar para a página de visualização da empresa.
2. Ao editar o valor de algum campo e clicar no Cancelar, o valor do campo deve continuar sendo o anterior.
Ex:. Alterei o valor do campo Número de 200 para 100 e cliquei no cancelar, o valor  deve continuar sendo 200.

**Comment by pedrro** [comment]
O que está acontecendo? Qual o comportamento esperado?
