### ISSUE TITLE
Campo "número" não aceita letras

### ISSUE THREAD

**Issue by inajaraleppa** [ThoughtWorksInc/registrolivre#97]
Ao criar ou editar uma empresa, se for inserido algum caracter não-numérico no campo de número, o cadastro/edição é concluído mas o campo não é salvo ou é salvo incompleto.

Nota:
Essa funcionalidade foi validada com o PO e ele decidiu que o número deve salvar caracteres alfanuméricos, visto que em alguns estados o número da casa podem seguir este formato.

**Para reproduzir o comportamento:**

1.
- Acessa o site do registro livre. http://10.27.1.58:5000/
- Entra na página Cadastrar Empresa
- Preenche o campo número com *"A22"*
- Preenche informações válidas nos outros campos
- Visita a página da empresa criada
- O campo número estará vazio

2.
- Acessa o site do registro livre. http://10.27.1.58:5000/
- Entra na página Cadastrar Empresa
- Preenche o campo número com "22A"
- Preenche informações válidas nos outros campos
- Visita a página da empresa criada
- O campo número estará com o valor "22"

3.
- Acessa o site do registro livre. http://10.27.1.58:5000/
- Entra na página da empresa a ser editada
- Modifica o campo número para "22A"
- Visita a página da empresa criada
- O campo número estará com o valor "22"

4.
- Acessa o site do registro livre. http://10.27.1.58:5000/
- Entra na página da empresa a ser editada
- Modifica o campo número para *"A22"*
- Visita a página da empresa criada
- O campo número estará vazio

**Comportamento esperado:**
Quando editar/cadastrar uma empresa, o campo número deve salvar os caracteres alfanuméricos, sem restrições de letras.

**Comment by josigama** [comment]
Ao corrigir o bug número #97 verifiquei que os testes unitários estavam cobrindo o problema. 
Temos o teste: 'should accepts digit + letters' que deveria estar capturando este problema, pois o bug se referia exatamente a este teste. 

Quando eu iniciava digitando letras e números ( E4455), o sistema não estava salvando o que foi digitado, porém se eu digitada primeiramente números e depois letras ( 44444EE), o sistema estava salvando apenas os números e ignorava as letras. 

Estamos com um teste falso positivo e devemos investigar qual o problema.
